### ISSUE TITLE
Amélioration de la config

### ISSUE THREAD

**Issue by dominiquevilain** [SwithFr/swithMVC#2]
Une première chose que tu pourrais faire est de gérer des environnements.

Tu pourrais ainsi créer plusieurs fichiers .env, en fonction de ton environnement courant (dev, prod, test, etc.) qui déclareraient les valeurs des variables relatives à l’environnement. De cette manière, tu pourrais sortir tes données de config pour la DB de ta class AppConfig et les placer dans un fichier qui ne serait pas soumis au contrôle de version. Pour réutiliser les valeurs en question, php propose des fonctions toutes faites (http://php.net/manual/fr/function.getenv.php) et des variables prédéfinies(http://php.net/manual/en/reserved.variables.environment.php).

Un première amélioration pas trop compliquée qui améliorerait la souplesse de ton framework.

**Comment by SwithFr** [comment]
Ok merci pour cette idée, je n'y avais pas pensé et c'est en effet une très bonne idée. 
J'ai apporté quelques modifications à la class AppConfig qui est à présent un singleton, je sais pas si c'est une bonne idée mais il m'a semblé plus logique de n'avoir qu'une seule instance de l'app.

Je vais vite regarder les variables d'environnement. 
Encore merci.

**Comment by SwithFr** [comment]
Bon voilà j'ai bricolé un peu le code pour pouvoir gérer plusieurs environnements, je suis pas certain d'avoir fait un truc optimisé mais j'améliorerai au fur et à mesure.

**Comment by dominiquevilain** [comment]
C’est l’idée :)
