### ISSUE TITLE
Les options de la requêtes sont effacées lors de paginate()

### ISSUE THREAD

**Issue by Fllorent0D** [SwithFr/swithMVC#3]
Solution
$conditions = array_merge($conditions, ["offset" => $nbPerPage \* ($_GET['page'] - 1)], ["limit" => $nbPerPage]);

**Comment by SwithFr** [comment]
Hum, je vois pas trop où est le probleme dans la fonction paginate() :/

**Comment by Fllorent0D** [comment]
Ca ne marche pas sur OVH :/
