### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Fllorent0D** [SwithFr/swithMVC#9]
Impossible de faire fonctionner le router avec des routes qui n'ont pas de paramètres.

**Comment by SwithFr** [comment]
Ce router va me rendre fou, j'ai jamais de problème avec moi ^^ 
Tu as un exemple qui produit le bug ? que je puisse checker

**Comment by Fllorent0D** [comment]
J'ai essayé un truc assez simple, mais j'ai débuggé un peu et le preg_match dans Router.php qui détermine si on la bonne route ne fonctionne pas j'ai l'impression 😕

Je vais essayer de le réécrire à ma sauce et je te dis quoi 😊

**Comment by SwithFr** [comment]
:'( J'ai jamais eu ce problème et pourtant j'utilise toujours les routes, tu as bien mis le USE_ROUTES à true dans la config de l'environnement ?

**Comment by Fllorent0D** [comment]
Ouais 😕 mais j'utilise php7 c'est peut être ça 😕

**Comment by SwithFr** [comment]
Nope je suis aussi passé sur php7 j'ai pas le pb :'(

**Comment by Fllorent0D** [comment]
je vais chercher plus en détail demain

**Comment by SwithFr** [comment]
Je pense avoir résolu le problème. Je me suis un peu emmêlé les pinceaux avec les branches ... à partir de la branch master tu devrais plus avoir de soucis. Dis moi si c'est tout bon ;)

**Comment by Fllorent0D** [comment]
Yep ca a aidé, c'est parfait merci  👍
